databases:
  - name: cea-api-postgre
    plan: free
    databaseName: cea_db_ftqe
    user: cea_db_ftqe_user

services:
  - type: web
    name: cea-api
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn school_admin.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cea-api-postgre
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: "school_admin.settings"
